apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
        - name: test
          image: test/nodejs
          ports:
          - containerPort: 9102
          - containerPort: 5858
          command:
          - npm
          args:
          - run
          - dev
          env:
          - name: NODE_ENV
            value: development
